### ISSUE TITLE
latest nuxt3 not working

### ISSUE THREAD

**Issue by userquin** [antfu/vitesse-nuxt3#21]
cloning the repo and installing deps will update to use latest version with this error, it seems nuxt3 not fully compatible with pnpm:

<details>
<summary><strong>error with nuxt3 3.0.0-27428764.271289c</strong></summary>

```shell
exports is not defined                                                                                                 
  at $id_56a97886 (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:130:23)            
  at __instantiateModule__ (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24647:9)  
  at __ssrLoadModule__ (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24594:25)     
  at ssrImport (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24619:13)
  at $id_39fc60f4 (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:32:37)
  at __instantiateModule__ (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24647:9)
  at __ssrLoadModule__ (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24594:25)
  at ssrImport (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24619:13)
  at ssrDynamicImport (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:24630:12)
  at file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:10:31
m.default is not a function
  at file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/dist/server/server.mjs:10:185
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderToString (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/node_modules/.pnpm/vue-bundle-renderer@0.3.5/node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
  at async renderMiddleware (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/.nuxt/nitro/index.mjs:206:20)
  at async handle (file:///F:/work/projects/quini/nuxt3/nuxt3-vuetify3/node_modules/.pnpm/h3@0.3.9/node_modules/h3/dist/index.mjs:601:19)
```
</details>

using previous version just works:
```shell
devDependencies:
- nuxt3 3.0.0-27428764.271289c
+ nuxt3 3.0.0-27393784.b110c8c (3.0.0-27428764.271289c is available)
```

**Comment by mikeshi80** [comment]
same problem, any update?

**Comment by mikeshi80** [comment]
I think it should be caused by this [issue](https://github.com/nuxt/framework/issues/3468), in my case, I put the project in the "nuxt3" folder. The problem is resolved since I rename the parent folder from "nuxt3" to "nuxt3-study", I hope this message is useful for you.
