### ISSUE TITLE
404 page generates an error

### ISSUE THREAD

**Issue by snoopyx** [antfu/vitesse-nuxt3#40]
After the app is built using "nuxi build" and started by "node .output/server/index.mjs" an error occurs:

[nitro] Error while generating error response FetchError: 404  (/__nuxt_error?url=/_nuxt/__vite_ping&statusCode=404&statusMessage=Cannot+find+static+asset+/_nuxt/__vite_ping&message=Cannot+find+static+asset+/_nuxt/__vite_ping&description)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.errorhandler [as onError] (file:///home/xxxxx/source/xxxxx/app/.output/server/chunks/nitro/node-server.mjs:310:16)
    at async Server.nodeHandler (file:///home/xxxxx/source/xxxxx/app/.output/server/node_modules/h3/dist/index.mjs:370:9)

**Comment by Developer27149** [comment]
Me too.

**Comment by szvest** [comment]
Add a `div` around `main`.

**Comment by SpiritUrban** [comment]
i have the same problem

**Comment by antfu** [comment]
Please keep track on https://github.com/nuxt/framework/issues/4940
