### ISSUE TITLE
The requested module 'vue' does not provide an export named 'default'

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [antfu/vitesse-nuxt3#61]
### Describe the bug

The current state of the repo is broken with the error:
```
The requested module 'vue' does not provide an export named 'default'

at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
```

### Reproduction

https://stackblitz.com/github/antfu/vitesse-nuxt3

### System Info

```Shell
OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 15.85 GB / 31.90 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yufanzheng0723** [comment]
Hi, I don't know if you used auto-import, the last time I reported this error was because there was something wrong with this auto-import

**Comment by yufanzheng0723** [comment]
If you use a component library, such as element-plus, and use auto-import, you can check if the component is not imported successfully

**Comment by AndrewBogdanovTSS** [comment]
@yufanzheng0723 I provided a repo that you can check what exact libs and settings I use.

**Comment by Axing-nxr** [comment]
solved?

**Comment by sgaconsultores** [comment]
Any news? I have this error in a fresh cloned project after npm install

`> postinstall
> nuxt prepare

Nuxi 3.5.0                                                                                                                                                                                             6:35:08 PM

 ERROR  The requested module 'vue' does not provide an export named 'computed'                                                                                                                         6:35:09 PM

  import { getCurrentInstance, inject, onUnmounted, onDeactivated, onActivated, computed, unref, watchEffect, defineComponent, reactive, h, provide, ref, watch, shallowRef, nextTick } from 'vue';
  ^^^^^^^^
  SyntaxError: The requested module 'vue' does not provide an export named 'computed'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
`

**Comment by g1ronn1mo** [comment]
Try pnpm instead

**Comment by antfu** [comment]
Is this problem still reproducible?

**Comment by cirolosapio** [comment]
i've deployed a nuxt app with coolify+docker and it happens
is there something i can try ? 

~repo~

```
[request error] [unhandled] [GET] https://ecommerce.crewbe.com/__nuxt_error?error=true&url=%2F&statusCode=500&statusMessage=Server+Error&message=Server+Error
 file:///app/server/chunks/build/server.mjs:1
import require$$0, { defineComponent, createElementBlock, unref, mergeProps, withCtx, renderSlot, ref as ref$1, toValue, watch, shallowReadonly, hasInjectionContext, inject, computed, getCurrentInstance, provide, isRef, reactive, h, useSSRContext, toRefs, Suspense, Fragment, createApp, createVNode, createTextVNode, shallowReactive, defineAsyncComponent, toRef, onErrorCaptured, onServerPrefetch, resolveDynamicComponent, effectScope, shallowRef, isReadonly, isShallow, isReactive, toRaw, getCurrentScope } from 'vue';
       ^^^^^^^^^^
SyntaxError: The requested module 'vue' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:182:21)
    ... 6 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///app/server/chunks/nitro/nitro.mjs:2244:7) {
  cause: file:///app/server/chunks/build/server.mjs:1
  import require$$0, { defineComponent, createElementBlock, unref, mergeProps, withCtx, renderSlot, ref as ref$1, toValue, watch, shallowReadonly, hasInjectionContext, inject, computed, getCurrentInstance, provide, isRef, reactive, h, useSSRContext, toRefs, Suspense, Fragment, createApp, createVNode, createTextVNode, shallowReactive, defineAsyncComponent, toRef, onErrorCaptured, onServerPrefetch, resolveDynamicComponent, effectScope, shallowRef, isReadonly, isShallow, isReactive, toRaw, getCurrentScope } from 'vue';
         ^^^^^^^^^^
  SyntaxError: The requested module 'vue' does not provide an export named 'default'
      at ModuleJob._instantiate (node:internal/modules/esm/module_job:182:21)
      at async ModuleJob.run (node:internal/modules/esm/module_job:266:5)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
      at async file:///app/server/chunks/nitro/nitro.mjs:5393:24
      at async Object.render (file:///app/server/chunks/routes/renderer.mjs:99:20)
      at async Object.handler (file:///app/server/chunks/nitro/nitro.mjs:5639:22)
      at async Object.handler (file:///app/server/chunks/nitro/nitro.mjs:1973:19)
      at async Server.toNodeHandle (file:///app/server/chunks/nitro/nitro.mjs:2244:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

```json
{
  "name": "nuxt-app-prod",
  "version": "0.0.0",
  "type": "module",
  "private": true,
  "dependencies": {
    "@algolia/events": "4.0.1",
    "@babel/parser": "7.27.2",
    "@babel/runtime": "7.27.1",
    "@fastify/accept-negotiator": "1.1.0",
    "@floating-ui/core": "1.7.0",
    "@floating-ui/dom": "1.7.0",
    "@floating-ui/utils": "0.2.9",
    "@floating-ui/vue": "1.1.6",
    "@iconify/vue": "5.0.0",
    "@internationalized/date": "3.8.0",
    "@internationalized/number": "3.6.1",
    "@stripe/stripe-js": "7.3.0",
    "@swc/helpers": "0.5.17",
    "@tanstack/virtual-core": "3.13.8",
    "@tanstack/vue-virtual": "3.13.8",
    "@trysound/sax": "0.2.0",
    "@vue/compiler-core": "3.5.14",
    "@vue/compiler-dom": "3.5.14",
    "@vue/compiler-ssr": "3.5.14",
    "@vue/devtools-api": "6.6.4",
    "@vue/reactivity": "3.5.14",
    "@vue/runtime-core": "3.5.14",
    "@vue/runtime-dom": "3.5.14",
    "@vue/server-renderer": "3.5.14",
    "@vue/shared": "3.5.14",
    "@vueuse/core": "12.8.2",
    "@vueuse/shared": "12.8.2",
    "algoliasearch-helper": "3.25.0",
    "aria-hidden": "1.2.6",
    "boolbase": "1.0.0",
    "class-variance-authority": "0.7.1",
    "clsx": "2.1.1",
    "color": "4.2.3",
    "color-convert": "2.0.1",
    "color-name": "1.1.4",
    "color-string": "1.9.1",
    "cookie-es": "1.2.2",
    "css-select": "5.1.0",
    "css-tree": "2.3.1",
    "css-what": "6.1.0",
    "csso": "5.0.5",
    "defu": "6.1.4",
    "destr": "2.0.5",
    "detect-libc": "2.0.4",
    "devalue": "5.1.1",
    "dom-serializer": "2.0.0",
    "domelementtype": "2.3.0",
    "domhandler": "5.0.3",
    "domutils": "3.2.2",
    "embla-carousel": "8.6.0",
    "embla-carousel-reactive-utils": "8.6.0",
    "embla-carousel-vue": "8.6.0",
    "entities": "4.5.0",
    "estree-walker": "2.0.2",
    "etag": "1.8.1",
    "h3": "1.15.3",
    "hookable": "5.5.3",
    "image-meta": "0.2.1",
    "instantsearch-ui-components": "0.11.1",
    "instantsearch.js": "4.78.3",
    "ipx": "2.1.0",
    "iron-webcrypto": "1.2.1",
    "is-arrayish": "0.3.2",
    "lucide-vue-next": "0.511.0",
    "mdn-data": "2.0.30",
    "mitt": "2.1.0",
    "node-fetch-native": "1.6.6",
    "node-mock-http": "1.0.0",
    "nth-check": "2.1.1",
    "ofetch": "1.4.1",
    "ohash": "2.0.11",
    "pathe": "1.1.2",
    "perfect-debounce": "1.0.0",
    "preact": "10.26.6",
    "qs": "6.9.7",
    "radix3": "1.1.2",
    "reka-ui": "2.2.1",
    "semver": "7.7.2",
    "sharp": "0.32.6",
    "simple-swizzle": "0.2.2",
    "source-map-js": "1.2.1",
    "svgo": "3.3.2",
    "tailwind-merge": "3.3.0",
    "ufo": "1.6.1",
    "uncrypto": "0.1.3",
    "unhead": "2.0.9",
    "vue": "3.5.14",
    "vue-bundle-renderer": "2.1.1",
    "vue-demi": "0.14.10",
    "vue-router": "4.5.1",
    "vue-sonner": "2.0.0"
  }
```

**Comment by cirolosapio** [comment]
![Image](https://github.com/user-attachments/assets/fe877f69-dd14-4759-92cf-200450aa7098)
this fixes the issue
