### ISSUE TITLE
[Error: Cannot find module @nuxt/kit] 

### ISSUE THREAD

**Issue by moHaHa** [antfu/vitesse-nuxt3#89]
### Describe the bug

I just `degit antfu/vitesse-nuxt3` aah-nuext3, then in `/aah-nuext3` 
I run `pnpm i` as you can see 

```
$ pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +1166
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\Mohammad\AppData\Local\pnpm\store\v3 
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1166, reused 1162, downloaded 0, added 1166, done

dependencies:
+ vue-tsc 1.2.0

devDependencies:
+ @antfu/eslint-config 0.38.4
+ @iconify-json/carbon 1.1.16
+ @iconify-json/twemoji 1.1.11
+ @nuxt/devtools 0.4.0
+ @nuxtjs/color-mode 3.2.0
+ @pinia/nuxt 0.4.8
+ @unocss/eslint-config 0.51.4
+ @unocss/nuxt 0.51.4
+ @vite-pwa/nuxt 0.0.7
+ @vueuse/nuxt 9.13.0
+ consola 3.0.1
+ eslint 8.38.0
+ nuxt 3.4.0
+ pinia 2.0.34
+ typescript 4.9.5

> @ postinstall C:\Users\Mohammad\source\mhacd-jameel\#1-Almodon-Alarabia-Holding\aah-nuxt3
> nuxi prepare

Nuxi 3.4.0                                                                               4:18:54 AM

[4:18:55 AM]  ERROR  Error: Cannot find module @nuxt/kit imported from file:///C:/Users/Mohammad/source/mhacd-jameel/#1-Almodon-Alarabia-Holding/aah-nuxt3/node_modules/.pnpm/nuxt@3.4.0_@types+node@18.14.0_eslint@8.38.0_rollup@2.79.1_typescript@4.9.5_vue-tsc@1.2.0/node_modules/nuxt/dist/index.mjs, file:///C:/Users/Mohammad/source/mhacd-jameel/, file:///C:/Users/Mohammad/source/mhacd-jameel/_index.js, file:///C:/Users/Mohammad/source/mhacd-jameel/node_modules

  at resolvePath (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/aah-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/shared/nuxi.da4c08ec.mjs:7513:10)
  at importModule (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/aah-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/shared/nuxi.1d8d2e21.mjs:11:30)
  at loadKit (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/aah-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/shared/nuxi.0318c2bd.mjs:7:18)
  at async Object.invoke (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/aah-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/chunks/prepare.mjs:31:26)
  at async _main (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/aah-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/cli.mjs:47:20)


 ELIFECYCLE  Command failed with exit code 1.
``` 

### Reproduction

local

### System Info

```Shell
nodejs : v16.15.1
windows : 10
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by moHaHa** [comment]
I update nodejs to  v18.16.0 , then I tried again
I got the same error 🚨

**Comment by moHaHa** [comment]
I just was reading my issue , I felt like why  I mentioned my project folder name, anyways .... after few minutes when I was reading the error I noteced something  why this error inclode path that out of my projects dir 

> `file:///C:/Users/Mohammad/source/mhacd-jameel/`

so I try to `degit` it in other dir `C:\Users\Mohammad\source\Nuxt` as  `try-vitesse-nuxt3` 
then run `pnpm i `

**and this worked fine**  ✅

![image](https://user-images.githubusercontent.com/72744132/236382287-f9e2dac3-d29c-4cb9-a2d8-9690e12d49cb.png)

**Comment by zhang771** [comment]
install it, then try again

**Comment by moHaHa** [comment]
@zhang771 
```
$ pnpm i  @nuxt/kit
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
 WARN  deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
Packages: +9 -1
+++++++++-
Progress: resolved 1217, reused 1187, downloaded 8, added 9, done

dependencies:
+ @nuxt/kit 3.4.3

Done in 1m 32.3s

Mohammad@DESKTOP-C3DO6N4 MINGW64 ~/source/mhacd-jameel/#1-Almodon-Alarabia-Holding/try-vitesse-nuxt3 (main)
$ pnpm i
Lockfile is up to date, resolution step is skipped
Already up to date

> @ postinstall C:\Users\Mohammad\source\mhacd-jameel\#1-Almodon-Alarabia-Holding\try-vitesse-nuxt3
> nuxi prepare

Nuxi 3.4.0                                                                                                          7:42:43 AM

[7:42:44 AM]  ERROR  Error: Cannot find module @nuxt/kit imported from file:///C:/Users/Mohammad/source/mhacd-jameel/#1-Almodon-Alarabia-Holding/try-vitesse-nuxt3/node_modules/.pnpm/nuxt@3.4.0_@types+node@18.14.0_eslint@8.38.0_rollup@2.79.1_typescript@4.9.5_vue-tsc@1.2.0/node_modules/nuxt/dist/index.mjs, file:///C:/Users/Mohammad/source/mhacd-jameel/, file:///C:/Users/Mohammad/source/mhacd-jameel/_index.js, file:///C:/Users/Mohammad/source/mhacd-jameel/node_modules

  at resolvePath (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/try-vitesse-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/shared/nuxi.da4c08ec.mjs:7513:10)
  at importModule (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/try-vitesse-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/shared/nuxi.1d8d2e21.mjs:11:30)
  at loadKit (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/try-vitesse-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/shared/nuxi.0318c2bd.mjs:7:18)
  at async Object.invoke (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/try-vitesse-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/chunks/prepare.mjs:31:26)
  at async _main (/C:/Users/Mohammad/source/mhacd-jameel/%231-Almodon-Alarabia-Holding/try-vitesse-nuxt3/node_modules/.pnpm/nuxi@3.4.0/node_modules/nuxi/dist/cli.mjs:47:20)

 ELIFECYCLE  Command failed with exit code 1.

```
