### ISSUE TITLE
rxjs error in nuxt3

### ISSUE THREAD

**Issue by transtone** [antfu/vitesse-nuxt3#91]
### Describe the bug

```cmd
[nuxt] [request error] [unhandled] [500] Cannot find module './internal/Observable'                                                                                                                                         17:34:59  
Require stack:
- D:\code\github\vitesse-nuxt3-main\rxjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Module._load (node:internal/modules/cjs/loader:920:27)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at D:\code\github\vitesse-nuxt3-main\rxjs:17:20
  at ViteNodeRunner.directRequest (/D:/code/github/vitesse-nuxt3-main/node_modules/.pnpm/vite-node@0.30.1_@types+node@18.14.0/node_modules/vite-node/dist/client.mjs:331:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (/D:/code/github/vitesse-nuxt3-main/node_modules/.pnpm/vite-node@0.30.1_@types+node@18.14.0/node_modules/vite-node/dist/client.mjs:171:14)
  at async ViteNodeRunner.dependencyRequest (/D:/code/github/vitesse-nuxt3-main/node_modules/.pnpm/vite-node@0.30.1_@types+node@18.14.0/node_modules/vite-node/dist/client.mjs:220:14)
  at async D:\code\github\vitesse-nuxt3-main\node_modules\.pnpm\@vueuse+rxjs@10.1.2_rxjs@7.8.1_vue@3.2.47\node_modules\@vueuse\rxjs\index.mjs:1:31
```

### Reproduction

https://github.com/transtone/vitesse-nuxt3

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 9.87 GB / 31.86 GB
  Binaries:
    Node: 18.15.0 - D:\bin\nodejs\node.EXE
    Yarn: 1.22.19 - D:\bin\nodejs-bin\yarn.CMD
    npm: 9.6.5 - D:\bin\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by transtone** [comment]
Reproduction is up to date.

**Comment by transtone** [comment]
It's a rxjs loading problem. add this in `nuxt.config.js`

```js
build: {
    transpile: ['rxjs']
},
```
https://nuxt.com/docs/guide/concepts/esm#transpiling-libraries
